game:
  game_rule: v1.2
  max_time: 100
  interaction_model:
    tagging: both_kill
    capture: kill
    prioritize: tagging
  payoff_model:
    model: zero_sum_reward
    constants:
      red_capture: 1.0
      blue_capture: 1.0
      red_killed: 0.5
      blue_killed: 0.5
agents:
  red_global:
    speed: 1
    capture_radius: 2
    sensing_radius: 400
    sensors:
    - global_map
    - candidate_flag
    - agent
    - name: egocentric_flag
      model: red_flag_r400
      carrier: agent
      flags: real
    - egocentric_flag_region
  blue_global:
    speed: 1
    tagging_radius: 1
    sensing_radius: 250
    sensors:
    - global_map
    - custom_team
    - name: egocentric_agent
      model: blue_agent_r250
      carrier: agent
      team: blue
    - egocentric_agent_region
    - flag
    - name: stationary
      model: blue_tower_r450
      at: blue_static_sensor_positions
  red_config:
    red_0:
      start_node_id: 101
    red_1:
      start_node_id: 139
    red_2:
      start_node_id: 70
    red_3:
      start_node_id: 174
    red_4:
      start_node_id: 148
  blue_config:
    blue_0:
      start_node_id: 4
    blue_1:
      start_node_id: 85
    blue_2:
      start_node_id: 193
    blue_3:
      start_node_id: 26
    blue_4:
      start_node_id: 184
flags:
  real_positions:
  - 11
  candidate_positions: &id001
  - 11
  - 144
  - 8
environment:
  graph_name: osm_200_a.pkl
  blue_stationary_sensor_radius: 450
  blue_static_sensor_positions: *id001
  visibility_models:
    red_flag_r400:
      type: line_of_sight
      crs: EPSG:32618
      max_range: 400
    blue_agent_r250:
      type: line_of_sight
      crs: EPSG:32618
      max_range: 250
    blue_tower_r450:
      type: line_of_sight
      crs: EPSG:32618
      max_range: 450
generator:
  id: 5411eaf1a2
  ts: '2026-07-13 23:25:51'
  cafl:
  - 12
  - 3
  - normal_t
  - 2
  - 1
  - 1.0
  reag:
  - 12
  - 5
  - normal_t
  - 10
  - 2
  - 1
  blag:
  - 12
  - 5
  - normal_t
  - 3
  - 1
  - 1
