game:
  game_rule: test
  max_time: 300
  interaction_model:
    tagging: both_kill
    capture: kill
    prioritize: tagging
  payoff_model:
    model: zero_sum_reward
    constants:
      red_capture: 1.0
      blue_capture: 1.0
      red_killed: 0.5
      blue_killed: 0.5
agents:
  red_global:
    speed: 1
    capture_radius: 2
    sensing_radius: 20
    sensors:
    - global_map
    - candidate_flag
    - agent
    - egocentric_flag
    - egocentric_map
  blue_global:
    speed: 1
    tagging_radius: 1
    sensing_radius: 30
    sensors:
    - global_map
    - custom_team
    - egocentric_agent
    - egocentric_map
    - flag
    - stationary
  red_config:
    red_0:
      start_node_id: 38
  blue_config:
    blue_0:
      start_node_id: 0
flags:
  real_positions:
  - 0
  candidate_positions: &id001
  - 0
  - 10
  - 24
environment:
  graph_name: wp_range16_0414.pkl
  blue_stationary_sensor_radius: 1
  blue_static_sensor_positions: *id001
generator: {}
